# Generated by Django 5.1.6 on 2025-11-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Fort', 'Fort'), ('Beach', 'Beach'), ('Waterfall', 'Waterfall'), ('Temple', 'Temple'), ('Viewpoint', 'Viewpoint'), ('Food', 'Food Spot'), ('Other', 'Other')], max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='destinations/main/')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('travel_tips', models.TextField(blank=True)),
                ('entry_fees', models.CharField(blank=True, default='Free', max_length=200)),
                ('timings', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.destination')),
            ],
        ),
    ]
