# Generated by Django 5.2.17 on 2026-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_is_verified_destination_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Fort', 'Fort'), ('Beach', 'Beach'), ('Waterfall', 'Waterfall'), ('Temple', 'Temple'), ('Viewpoint', 'Viewpoint'), ('Food', 'Food Spot'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
