# Generated by Django 5.2.17 on 2026-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/main/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/'),
        ),
    ]
