# Generated by Django 5.2.17 on 2026-09-13 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_main_image_alter_gallery_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_verified', '-created_at'], name='dest_verified_created_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_verified', 'category'], name='dest_verified_category_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category', '-created_at'], name='dest_category_created_idx'),
        ),
    ]
