# Generated by Django 6.0.1 on 2026-04-18 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0, help_text='Estimated cost or entry fee')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spots/')),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, default='Sunrise - Sunset', max_length=100, null=True)),
                ('closing_hours', models.CharField(blank=True, default='Sunset', max_length=100, null=True)),
                ('map_link', models.URLField(blank=True, help_text='Google Maps URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spots.category')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('tags', models.ManyToManyField(blank=True, to='spots.tag')),
            ],
        ),
    ]
