# Generated by Django 5.1.6 on 2025-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spots_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spots/'),
        ),
    ]
