# Generated by Django 6.0.1 on 2026-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_alter_spots_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='spots',
            name='closing_hours',
            field=models.CharField(blank=True, default='Sunset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spots',
            name='opening_hours',
            field=models.CharField(blank=True, default='Sunrise - Sunset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spots',
            name='price',
            field=models.FloatField(default=0.0, help_text='Estimated cost or entry fee'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spots',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps URL', null=True),
        ),
    ]
