# Generated by Django 6.0.1 on 2026-02-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_remove_spots_ingredients_spots_closing_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spots.category'),
        ),
    ]
