# Generated by Django 5.2.17 on 2026-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_alter_spots_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spots',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='spots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='spots',
            index=models.Index(fields=['-rating'], name='spots_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='spots',
            index=models.Index(fields=['-created_at'], name='spots_created_idx'),
        ),
        migrations.AddIndex(
            model_name='spots',
            index=models.Index(fields=['name'], name='spots_name_idx'),
        ),
    ]
