# Generated by Django 5.2.17 on 2026-09-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0003_alter_destination_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Ratnagiri District Civil Hospital', max_length=200)),
                ('category', models.CharField(choices=[('POLICE', 'Police & Coastal Security'), ('HOSPITAL', 'Hospital & Medical Emergency (24x7)'), ('AMBULANCE', 'Ambulance & Emergency Response'), ('FIRE', 'Fire & Rescue'), ('TOURIST_HELPLINE', 'Tourist Assistance Helpline'), ('COASTAL_POLICE', 'Marine & Coastal Rescue'), ('TOWING', 'Vehicle Breakdown & Towing')], db_index=True, default='HOSPITAL', max_length=30)),
                ('phone_number', models.CharField(help_text='Primary telephone or SOS number (e.g. +91 2352 222333 or 112)', max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_24x7', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g., Sea forts, tranquil beaches and authentic Malvani thalis', max_length=250)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days (e.g., 1, 2, 3)')),
                ('audience', models.CharField(choices=[('ALL', 'All Travelers'), ('FAMILY', 'Family with Kids'), ('COUPLE', 'Couples & Romantic'), ('BUDGET', 'Budget & Backpackers'), ('SOLO', 'Solo Explorers'), ('FOODIE', 'Culinary & Food Trails'), ('HERITAGE', 'History & Fort Trail')], db_index=True, default='ALL', max_length=30)),
                ('season', models.CharField(choices=[('ALL', 'All Seasons'), ('WINTER', 'Winter (Nov - Feb)'), ('MONSOON', 'Monsoon Magic (Jun - Sep)'), ('SUMMER', 'Summer Coastal (Mar - May)')], db_index=True, default='ALL', max_length=30)),
                ('difficulty', models.CharField(choices=[('EASY', 'Relaxed & Easy Pace'), ('MODERATE', 'Moderate Sightseeing'), ('ACTIVE', 'Active & Adventurous')], default='EASY', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='itineraries/')),
                ('estimated_cost_inr', models.CharField(blank=True, default='₹1,500 - ₹3,500 / day', help_text='Estimated budget range', max_length=100)),
                ('total_distance_km', models.FloatField(default=0.0, help_text='Approximate travel distance in KM')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['order', 'duration_days', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('partner_type', models.CharField(choices=[('HOTEL', 'Hotel & Resort'), ('HOMESTAY', 'Authentic Homestay'), ('RESTAURANT', 'Restaurant & Café'), ('TOUR_OPERATOR', 'Tour Operator & Guide'), ('LOCAL_ARTISAN', 'Local Artisan & Mango/Cashew Store'), ('TRANSPORT', 'Transport & Taxi Service'), ('ATTRACTION', 'Attraction & Kiosk'), ('OTHER', 'Other Partner')], db_index=True, default='HOTEL', max_length=50)),
                ('short_tagline', models.CharField(blank=True, help_text='e.g., Beachfront luxury stay in Ganpatipule', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='partners/covers/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(help_text='e.g., Coastal Sea Forts & Sunset Horizons', max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='companion.itinerary')),
            ],
            options={
                'ordering': ['day_number', 'order'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, help_text='Override or custom stop name', max_length=200)),
                ('stop_type', models.CharField(choices=[('MORNING', 'Morning Exploration'), ('BREAKFAST', 'Local Breakfast'), ('SIGHTSEEING', 'Sightseeing Landmark'), ('BEACH', 'Beach Relaxation'), ('FORT', 'Historic Fort Trail'), ('LUNCH', 'Authentic Lunch'), ('ADVENTURE', 'Water Sports & Adventure'), ('SUNSET', 'Sunset Vantage Point'), ('SHOPPING', 'Local Market & Souvenirs'), ('DINNER', 'Coastal Dinner'), ('STAY', 'Resort / Homestay Check-in')], default='SIGHTSEEING', max_length=30)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('start_time', models.CharField(blank=True, default='09:00 AM', help_text='e.g. 09:00 AM', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated time spent in minutes')),
                ('activity_description', models.TextField(blank=True)),
                ('travel_note_to_next', models.CharField(blank=True, help_text='e.g. 15 min drive via coastal bypass', max_length=250)),
                ('travel_time_minutes', models.PositiveIntegerField(default=15, help_text='Estimated drive time to next stop')),
                ('map_lat', models.FloatField(blank=True, null=True)),
                ('map_lng', models.FloatField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, help_text='Local insider advice for this stop')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='companion.itineraryday')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_stops', to='destinations.destination')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(db_index=True, help_text='Short unique token, e.g., RATNA-HOTEL-01', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Descriptive tag name, e.g., Hotel Sea Breeze Room 102', max_length=200)),
                ('tag_type', models.CharField(choices=[('GENERAL', 'General Tourism NFC'), ('HOTEL', 'Hotel / Homestay Guest NFC'), ('RESTAURANT', 'Restaurant / Food Hub NFC'), ('ATTRACTION', 'Monument / Attraction NFC'), ('ITINERARY', 'Specific Itinerary NFC'), ('EMERGENCY', 'Safety & Emergency NFC'), ('FOOD_TRAIL', 'Food Trail NFC')], db_index=True, default='GENERAL', max_length=30)),
                ('target_experience', models.CharField(choices=[('HOME', 'Companion Home Gateway'), ('ITINERARIES', 'Itinerary Navigator'), ('NEAR_ME', 'Live GPS Near-Me Radar'), ('EXPLORE', 'Explore Hub & Categories'), ('EMERGENCY', '1-Click SOS Emergency Hub'), ('FOOD_TRAIL', 'Taste of Ratnagiri Food Trail'), ('SPECIFIC_ITINERARY', 'Direct Specific Itinerary'), ('SPECIFIC_DESTINATION', 'Direct Landmark Brief'), ('PARTNER_PAGE', 'Partner Welcome Concierge'), ('CUSTOM_URL', 'Custom External/Internal Route')], default='HOME', max_length=30)),
                ('custom_url', models.CharField(blank=True, help_text='Target URL path if custom_url is selected', max_length=255)),
                ('custom_welcome_title', models.CharField(blank=True, help_text='e.g. Welcome Guest of Hotel Sea Breeze!', max_length=200)),
                ('custom_welcome_message', models.TextField(blank=True, help_text='Personalized note displayed upon tap')),
                ('tap_count', models.PositiveIntegerField(default=0, help_text='Total taps recorded')),
                ('unique_visitor_count', models.PositiveIntegerField(default=0, help_text='Estimated unique sessions')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_tapped_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to='destinations.destination')),
                ('assigned_itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to='companion.itinerary')),
                ('assigned_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to='companion.partner')),
            ],
            options={
                'verbose_name': 'NFC Tag',
                'verbose_name_plural': 'NFC Tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCTapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_hash', models.CharField(blank=True, db_index=True, help_text='Anonymous daily session hash', max_length=64)),
                ('device_type', models.CharField(default='Mobile', max_length=30)),
                ('browser_family', models.CharField(blank=True, max_length=50)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.CharField(blank=True, default='tap_opened', max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='companion.nfctag')),
            ],
            options={
                'ordering': ['-tapped_at'],
            },
        ),
    ]
