# Generated by Django 5.2.17 on 2026-09-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('urgency_level', models.CharField(choices=[('INFO', 'Informational Notice'), ('WARNING', 'Travel Advisory / Tide Alert'), ('CRITICAL', 'Emergency / Heavy Weather Warning')], db_index=True, default='INFO', max_length=20)),
                ('link_url', models.CharField(blank=True, help_text='Optional target link URL', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General & Travel Guide'), ('TRANSPORT', 'Local Transport & Taxis'), ('FOOD', 'Cuisine, Seafood & Mango Season'), ('SAFETY', 'Beach Safety & Tides'), ('STAY', 'Homestays & Resorts'), ('NFC', 'NFC Tag & Companion Guide')], db_index=True, default='GENERAL', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('BEST_TIME', 'Best Time & Seasons'), ('PACKING', 'What to Pack & Essentials'), ('CULTURE', 'Local Etiquette & Marathi Phrases'), ('SAVINGS', 'Budget Hacks & Dining Tips'), ('PHOTO', 'Photography & Sunset Vantage')], db_index=True, default='BEST_TIME', max_length=50)),
                ('icon', models.CharField(default='fa-lightbulb', help_text='FontAwesome icon class, e.g. fa-umbrella-beach', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created Object'), ('UPDATE', 'Updated Object'), ('DELETE', 'Deleted Object'), ('STATUS_CHANGE', 'Status Changed'), ('BULK_ACTION', 'Bulk Generated / Batch Action'), ('VERIFY', 'Verification Status Changed')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, help_text='e.g. Place, Itinerary, NFC Tag, Partner', max_length=50)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
