# Generated by Django 5.2.17 on 2026-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_announcement_faq_traveltip_adminauditlog'),
        ('destinations', '0005_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-created_at'], name='ann_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['is_active', 'order'], name='emg_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['category', 'is_active'], name='emg_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_published', 'order'], name='faq_pub_order_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_published'], name='faq_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['is_active', 'order'], name='itin_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['is_active', 'duration_days'], name='itin_active_dur_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['is_active', 'audience'], name='itin_active_aud_idx'),
        ),
        migrations.AddIndex(
            model_name='nfctag',
            index=models.Index(fields=['is_active', '-tap_count'], name='nfc_active_taps_idx'),
        ),
        migrations.AddIndex(
            model_name='nfctag',
            index=models.Index(fields=['tag_type', 'is_active'], name='nfc_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='nfctapevent',
            index=models.Index(fields=['tag', 'session_hash'], name='tap_tag_session_idx'),
        ),
        migrations.AddIndex(
            model_name='nfctapevent',
            index=models.Index(fields=['tag', '-tapped_at'], name='tap_tag_tapped_idx'),
        ),
        migrations.AddIndex(
            model_name='nfctapevent',
            index=models.Index(fields=['-tapped_at'], name='tap_tapped_at_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active', '-is_featured'], name='partner_active_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type', 'is_active'], name='partner_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='traveltip',
            index=models.Index(fields=['is_active', 'order'], name='tip_active_order_idx'),
        ),
    ]
