# Generated by Django 5.2.17 on 2026-09-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_announcement_ann_active_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma-separated: Free Wi-Fi, Beach View, AC, Parking, Seafood, Pool', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='exclusive_offer',
            field=models.CharField(blank=True, help_text='e.g. 10% Off on Dining or Welcome Drink for Konkan Guide Explorers', max_length=250),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='e.g. @sawantvilla_konkan', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='offer_code',
            field=models.CharField(blank=True, help_text='e.g. KONKAN10', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='e.g. Check-in 12:00 PM / Check-out 10:00 AM', max_length=150),
        ),
        migrations.AddField(
            model_name='partner',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g. ?1,500 - ?3,500 / night or ?? Moderate', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps share link or location URL'),
        ),
    ]
