# Generated by Django 5.2.8 on 2025-11-13 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('rate', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
