# Generated by Django 5.2.8 on 2025-11-13 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_category_alter_spots_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='spots',
            name='rate',
        ),
        migrations.AddField(
            model_name='spots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spots',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spots_photos/'),
        ),
        migrations.AddField(
            model_name='spots',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spots',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='spot_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('map_location', models.URLField(blank=True, null=True)),
                ('opening_hours', models.CharField(max_length=100)),
                ('closing_hours', models.CharField(max_length=100)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.spots')),
            ],
        ),
    ]
