# Generated by Django 5.2.8 on 2025-11-15 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_tag_remove_spots_rate_spots_created_at_spots_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='category',
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='food_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category')),
                ('tags', models.ManyToManyField(blank=True, to='food.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True)),
                ('recipe_link', models.URLField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('best_time_to_eat', models.CharField(blank=True, max_length=100)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
            ],
        ),
        migrations.DeleteModel(
            name='spot_info',
        ),
        migrations.DeleteModel(
            name='Spots',
        ),
    ]
