# Generated by Django 5.2.8 on 2025-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_spots_category_fooditem_foodinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
