# Generated by Django 5.2.8 on 2025-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_foodinfo_description_fooditem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
