# Generated by Django 5.2.8 on 2025-11-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_fooditem_description_foodinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem'),
        ),
    ]
