# Generated by Django 5.2.8 on 2025-11-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_foodinfo_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem'),
        ),
    ]
