# Generated by Django 5.2.8 on 2025-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_foodinfo_description_alter_foodinfo_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='best_time_to_eat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='recipe_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FoodInfo',
        ),
    ]
