# Generated by Django 5.2.8 on 2025-11-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_fooditem_best_time_to_eat_fooditem_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(blank=True, default='default_food.jpg', null=True, upload_to=''),
        ),
    ]
