# Generated by Django 6.0.1 on 2026-02-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_fooditem_photo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
