# Generated by Django 6.0.1 on 2026-02-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_fooditem_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='recipe_link',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.model')),
        ),
    ]
