# Generated by Django 6.0.1 on 2026-02-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_fooditem_calories_remove_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
